services:
  product-service:
    build:
      context: ../..
      dockerfile: core-services/product-service/Dockerfile
    container_name: product-service
    env_file:
      - ./.env.docker
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8084:8084"
    restart: always
    depends_on:
      - config-server
      - eureka-server
    networks:
      - alpha_network
