services:
  product-service:
    image: ${DOCKER_USERNAME}/product-service:latest
    container_name: product-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      SPRING_CLOUD_CONFIG_URI: ${CONFIG_SERVER_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATASOURCE_URL: ${PRODUCT_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
    ports:
      - "8084:8084"
    restart: always
