name: Deploy Product Service

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "backend/core-services/product-service/**"
      - "backend/deploy/compose-product.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/core-services/product-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCT_SSH_HOST }}
          username: ${{ secrets.COMMON_EC2_SSH_USER }}
          key: ${{ secrets.COMMON_EC2_SSH_KEY }}
          port: ${{ secrets.COMMON_EC2_SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.PRODUCT_DEPLOY_PATH }}
            git pull origin main
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker compose -f backend/deploy/compose-product.yml up -d
