services:
  user-service:
    build:
      context: ../..
      dockerfile: core-services/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./.env.docker
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8086:8086"
    restart: always
    depends_on:
      - config-server
      - eureka-server
    networks:
      - alpha_network